apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: meu-nginx
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: ClusterIP
ubuntu@master01:~$ cat meu_first_service_node.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: meu-nginx
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32222
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
